# Importuri

In [1]:
from numpy.random import seed
seed(888)
# from tensorflow import set_random_seed
# set_random_seed(404)
import tensorflow as tf
tf.random.set_seed(404)


In [2]:
import os
import numpy as np
import tensorflow as tf

from time import strftime
from PIL import Image

# Constante

In [3]:
X_TRAIN_PATH = 'MNIST/digit_xtrain.csv'
X_TEST_PATH = 'MNIST/digit_xtest.csv'
Y_TRAIN_PATH = 'MNIST/digit_ytrain.csv'
Y_TEST_PATH = 'MNIST/digit_ytest.csv'

NR_CLASSES = 10
VALIDATION_SIZE = 10000
IMAGE_WIDTH = 28
IMAGE_HEIGHT = 28
CHANNELS = 1
TOTAL_INPUTS = IMAGE_WIDTH * IMAGE_HEIGHT * CHANNELS

# Optinerea Datelor

In [4]:
%%time
y_train_all = np.loadtxt(Y_TRAIN_PATH, delimiter=',', dtype=int)

Wall time: 248 ms


In [5]:
y_train_all.shape

(60000,)

In [6]:
y_test = np.loadtxt(Y_TEST_PATH, delimiter=',', dtype=int)

In [7]:
%%time
x_train_all = np.loadtxt(X_TRAIN_PATH, delimiter=',', dtype=int)

Wall time: 45 s


In [8]:
%%time

x_test = np.loadtxt(X_TEST_PATH, delimiter=',', dtype=int)

Wall time: 6.7 s


# Explorare

In [9]:
x_train_all.shape

(60000, 784)

In [10]:
x_train_all[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   3,  18,  18,  18,
       126, 136, 175,  26, 166, 255, 247, 127,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,  30,  36,  94, 154, 17

In [11]:
y_train_all.shape

(60000,)

In [12]:
x_test.shape

(10000, 784)

In [13]:
y_train_all[:5]

array([5, 0, 4, 1, 9])

# Data Pre-Procesare

In [14]:
# Re-scalare
x_train_all, x_test = x_train_all /255.0, x_test / 255.0# transforma int in float

# Convet valorile target catre one-hot encode

In [15]:
values = y_train_all[:5]
np.eye(10)[values]

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [16]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [17]:
np.eye(10)[2]

array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
values

array([5, 0, 4, 1, 9])

In [19]:
values[4]

9

In [20]:
y_train_all = np.eye(NR_CLASSES)[y_train_all]

In [21]:
y_train_all.shape

(60000, 10)

In [22]:
y_test = np.eye(NR_CLASSES)[y_test]

In [23]:
y_test.shape

(10000, 10)

# Creare Validare dataset din training data

** Provocare: ** Împărțit setul de date de formare într-un set de date de antrenament mai mic și un set de date de validare pentru caracteristici și etichete. Creați patru tablouri: `` `x_val```,` `y_val```,` `x_train``` și` `y_train``` de la` `x_train_all``` și` `y_train_all` ``. Utilizați dimensiunea de validare de 10.000.

In [24]:
x_val = x_train_all[:VALIDATION_SIZE]
y_val = y_train_all[:VALIDATION_SIZE]

In [25]:
x_train = x_train_all[VALIDATION_SIZE:]
y_train = y_train_all[VALIDATION_SIZE:]

In [26]:
x_train.shape

(50000, 784)

In [27]:
x_val.shape

(10000, 784)

# Tensor
# salar este o mărime fizică complet determinată numai prin valoarea sa numerică (număr real) si are un rank 0 
# o colona cu numere se numesc vectori/Array, acest array are o singura dimensiune si are un rank 1 
# cate o data avem mai multe numere si vom lucre cu data frame ori matrici ,aceasta matrice/dataframe are 2 dimensiuni adica randuri si coloane.si are un rank 2 
# cand adugam a treia dimensiune format din 3 matrici/dataframe => tensor. Un cub de numere. aseta are un rank 3.  este numit tesor tot ce are  3 dimensiuni sau mai multe dimensiuni

# Setup TensorFlow Graph

In [28]:
print('Versiunea de TensorFlow este', tf.__version__)
tf.compat.v1.disable_eager_execution()

Versiunea de TensorFlow este 2.1.0


# Codul de mai jos din versiunea de tensorflow V1 a fos re-scris pentru a functiona cu versiunea de tensorflow V2(v2.1.0)

In [29]:

X = tf.compat.v1.placeholder(tf.float32, shape=[None, TOTAL_INPUTS], name='X')#placehoder pentru features
Y = tf.compat.v1.placeholder(tf.float32, shape=[None, NR_CLASSES], name='labels')#placeholder pentru labels/categori

# Arhitectura  Neural Network
# Hyperparameters 
### Hiperrametrii sunt practic lucruri pe care le vom determina înainte de timp. Așadar, acestea sunt lucruri de genul cât timp ne antrenăm modelul pentru numărul de epoci utilizate pentru formarea ritmului de învățare utilizat în optimizatorul nostru, numărul de straturi din NN-ul nostru, numărul de noduri pe strat, toate aceste lucruri sunt hiperparametri

In [30]:
nr_epochs = 5
learning_rate = 0.0001 # in notatie stintifica acest 0.0001 este reprezentat de le-4

n_hidden1 = 512
n_hidden2 = 64
n_output = 10

# Metoda 1

initial_w1 = tf.compat.v1.truncated_normal(shape=[TOTAL_INPUTS, n_hidden1],stddev=0.1, seed=42)# initializare primului strat
w1 = tf.compat.v1.Variable(initial_value=initial_w1)# creare weights

initial_b1 = tf.compat.v1.constant(value=0.0, shape=[n_hidden1])#initializare bias
b1 = tf.compat.v1.Variable(initial_value=initial_b1) #crearea bias

layer1_in = tf.matmul(X,w1) + b1 # creaza features care merg in primul strat ascuns (hidden layer)

layer1_out = tf.nn.relu(layer1_in)# output pentru primul strat ascuns(hidden layer) este rezultatul calculat in aceasta funtie de activare

***Provocare***: configurați al doilea strat posterior. Acest strat are 64 de neuroni și trebuie să lucreze la ieșirea primului strat ascuns (vezi mai sus). Apoi configurați stratul de ieșire. Rețineți că acel strat de ieșire va folosi funcția de activare softmax.

initial_w2 = tf.compat.v1.truncated_normal(shape=[n_hidden1,n_hidden2],stddev=0.1, seed=42)# initializare al doilea strat
w2 = tf.compat.v1.Variable(initial_value=initial_w2)# creare weights

initial_b2 = tf.compat.v1.constant(value=0.0, shape=[n_hidden2])#initializare bias
b2 = tf.compat.v1.Variable(initial_value=initial_b2) #crearea bias

layer2_in = tf.compat.v1.matmul(layer1_out,w2) + b2 # creaza features care merg in al doilea strat ascuns (hidden layer)

layer2_out = tf.compat.v1.nn.relu(layer2_in)# output pentru al doilea strat ascuns(hidden layer) este rezultatul calculat in aceasta funtie de activare

initial_w3 = tf.compat.v1.truncated_normal(shape=[n_hidden2, n_output],stddev=0.1, seed=42)# initializare stratul de output
w3 = tf.Variable(initial_value=initial_w3)# creare weights

initial_b3 = tf.compat.v1.constant(value=0.0, shape=[n_output])#initializare bias
b3 = tf.compat.v1.Variable(initial_value=initial_b3) #crearea bias

layer3_in = tf.matmul(layer2_out, w3) + b3 # creaza features care merg in al treilea strat ascuns (hidden layer)

output = tf.compat.v1.nn.softmax(layer3_in)# output , rezultatul final

# Metoda 2

In [31]:
def setup_layer(input, weight_dim, bias_dim, name):
    
    with tf.name_scope(name):
        initial_w = tf.compat.v1.truncated_normal(shape=weight_dim, stddev=0.1, seed=42)
        w = tf.compat.v1.Variable(initial_value=initial_w, name='W')

        initial_b = tf.compat.v1.constant(value=0.0, shape=bias_dim)
        b = tf.compat.v1.Variable(initial_value=initial_b, name='B')

        layer_in = tf.matmul(input, w) + b
        
        if name=='out':
            layer_out = tf.nn.softmax(layer_in)
        else:
            layer_out = tf.nn.relu(layer_in)
        

        
        return layer_out

In [32]:
layer_1 = setup_layer(X, weight_dim=[TOTAL_INPUTS, n_hidden1], 
                      bias_dim=[n_hidden1], name='layer_1')

layer_drop = tf.compat.v1.nn.dropout(layer_1, keep_prob=0.8, name='dropout_layer')

layer_2 = setup_layer(layer_drop, weight_dim=[n_hidden1, n_hidden2], 
                      bias_dim=[n_hidden2], name='layer_2')

output = setup_layer(layer_2, weight_dim=[n_hidden2, NR_CLASSES], 
                      bias_dim=[NR_CLASSES], name='out')

model_name = f'{n_hidden1}-DO-{n_hidden2} LR{learning_rate} E{nr_epochs}'

Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


# Loss, Optimizare si Matrice

# Definirea functiei Loss

In [33]:
with tf.name_scope('loss_calc'):
    loss = tf.compat.v1.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels=Y, logits=output))

# Definirea optimizatorului

In [34]:
with tf.name_scope('optimizer'):   
    optimizer = tf.compat.v1.train.AdamOptimizer(learning_rate=learning_rate)# spunem ca optimizator folosim, initalizam optimizatorul
    
    train_step = optimizer.minimize(loss)# spunem care loss trebui sa fie minimalizat

## Maticea de acuratete

In [35]:
with tf.name_scope('accuracy_calc'):
    correct_pred = tf.equal(tf.argmax(output, axis=1), tf.argmax(Y, axis=1))
    accuracy = tf.reduce_mean(tf.cast(correct_pred, tf.float32))# calculare acuratetei

In [36]:
with tf.name_scope('performance'):
    tf.summary.scalar('accuracy', accuracy)
    tf.summary.scalar('cost', loss)

# Run Session

In [37]:
sess = tf.compat.v1.Session()

In [55]:
merged_summary = tf.compat.v1.summary.merge_all()


In [56]:
# Initializare toate variabilele
init = tf.compat.v1.global_variables_initializer()
sess.run(init)

w1.eval(sess)

b3.eval(sess)

# Batching the Data

In [57]:
size_of_batch = 1000

In [58]:
num_exemples = y_train.shape[0]
nr_iterations = int(num_exemples/size_of_batch)

index_in_epoch = 0

In [59]:
def next_batch(batch_size, data, labels):

    global num_exemples
    global index_in_epoch

    start = index_in_epoch
    index_in_epoch += batch_size # = index_in_epoch + batch_size

    if index_in_epoch > num_exemples:
        start=0
        index_in_epoch = batch_size

    end = index_in_epoch

    return data[start:end], labels[start:end]

# Training Loop

In [71]:
for epoch in range(nr_epochs):
    for i in range(nr_iterations):
        batch_x, batch_y = next_batch(batch_size=size_of_batch, data= x_train, labels=y_train)
        
        feed_dictionary = {X:batch_x,  Y:batch_y}
        
        sess.run(train_step, feed_dict=feed_dictionary)

        batch_accuracy = sess.run(fetches=[accuracy], feed_dict=feed_dictionary)
    
    print(f'Epoch {epoch} \t| Training Acuratete = {batch_accuracy}')
print('Done training')



Epoch 0 	| Training Acuratete = [0.921]
Epoch 1 	| Training Acuratete = [0.924]
Epoch 2 	| Training Acuratete = [0.924]
Epoch 3 	| Training Acuratete = [0.927]
Epoch 4 	| Training Acuratete = [0.93]
Done training


In [61]:
for epoch in range(nr_epochs):
    
    # ============= Training Dataset =========
    for i in range(nr_iterations):
        
        batch_x, batch_y = next_batch(batch_size=size_of_batch, data=x_train, labels=y_train)
        
        feed_dictionary = {X:batch_x, Y:batch_y}
        
        sess.run(train_step, feed_dict=feed_dictionary)
        
    
    batch_accuracy = sess.run(fetches=[ accuracy], feed_dict=feed_dictionary)
        
    #train_writer.add_summary(s, epoch)
    
    print(f'Epoch {epoch} \t| Training Accuracy = {batch_accuracy}')
    

    
    

print('Done training!')

Epoch 0 	| Training Accuracy = [0.502]
Epoch 1 	| Training Accuracy = [0.717]
Epoch 2 	| Training Accuracy = [0.743]
Epoch 3 	| Training Accuracy = [0.839]
Epoch 4 	| Training Accuracy = [0.889]
Done training!


# Face o predictie

In [62]:
img = Image.open('MNIST/test_img.png')
img

In [63]:
bw = img.convert('L')

In [64]:
img_array = np.invert(bw)

In [65]:
img_array.shape

(28, 28)

In [66]:
test_img = img_array.ravel()

In [67]:
test_img.shape

(784,)

In [68]:
prediction = sess.run(fetches=tf.argmax(output, axis=1), feed_dict={X:[test_img]})

In [69]:
print(f'Prediction for test image is {prediction}')

Prediction for test image is [2]


# Testarea si Evaluare

** Provocare: ** Calculați precizia peste setul de date de test (`` `x_test``` și` `` y_test```). Folosiți-vă cunoștințele despre rularea unei sesiuni pentru a obține precizia Afișați precizia ca un procent rotunjit la două numere zecimale.

In [70]:
test_accuracy = sess.run(fetches=accuracy, feed_dict={X:x_test, Y:y_test})
print(f'Accuracy on test set is {test_accuracy:0.2%}')

Accuracy on test set is 87.83%
